######################################################################
# Automatically generated by qmake (2.01a) Wed Apr 21 07:03:40 2010
######################################################################

QT       += core gui 

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets 

TEMPLATE = app
TARGET = screenshotqt
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp\
    cmdthread.cpp \
    screenshot.cpp

HEADERS  += \
    cmdthread.h \
    screenshot.h

include(install.pri)

