#!/usr/bin/env bash
#-----------------------------------------------------------------------------#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# This file is part of project auth-service (PTXdist package wago-auth-service).
#
# Copyright (c) 2024 WAGO GmbH & Co. KG
#-----------------------------------------------------------------------------#
#-----------------------------------------------------------------------------#
# Script:   /etc/config-tools/backup-restore/auth_service
#
# Brief:    Backup and restore config file for WAGO Auth Service.
#
# Author:   FHa: WAGO GmbH & Co. KG
#-----------------------------------------------------------------------------#
set -o nounset
set -o pipefail

BACKUP_PREFIX='authd'
SETTINGS_FILE='/etc/authd/authd.conf'

# List of the authd parameters for backup/restore
# one line with 2 parts for each parameter, parts seperated by ';'
# 1. part: parameter name in authd config file
# 2. part: parameter name in settings backup file
config_params=()

config_params+=(
    "auth_code.lifetime; auth_code.lifetime"
)
config_params+=(
    "access_token.lifetime; access_token.lifetime"
)
config_params+=(
    "refresh_token.lifetime; refresh_token.lifetime"
)
config_params+=(
    "silent_mode.enabled; silent_mode.enabled"
)
config_params+=(
    "system_use_notification; system_use_notification"
)


# load general definitions and functions
if [ ! -f "/etc/config-tools/config_tool_defines" ]; then
    print_dbg "config_tool_defines missing"
    exit 64
fi
source "/etc/config-tools/config_tool_defines"

function PrintUsage
{
    local self; self="$(basename "$0")"
    echo "${self} --save <backup-file>      backup authd settings"
    echo "${self} --restore <backup-file>   restore authd settings"
    echo "${self} --param-count             get number of authd parameters to save"
}

# Write logging data using syslog.
#
# Input: Message to log.
#
function Log
{
    [[ $# -gt 0 ]] && logger -t "$(basename "$0")" "$1"
}


#### Backup & Restore ##########################################################

# Get number of parameters that have to be saved during backup.
#
# output: 1.) number of parameters to save during backup.
#         2.) returns config tool status, see /etc/config-tools/config_tool_defines.
#
function GetParameterCount
{
    echo ${#config_params[*]}
    return $SUCCESS
}

# Save configuration parameters to backup file.
#
# input:  backup file path
# output: returns config tool status, see /etc/config-tools/config_tool_defines.
#
function Save
{
    local result=$SUCCESS
    local backup_file="$1"

    config_param_index=0
    while [[ $config_param_index -lt ${#config_params[*]} ]]; do
        local config_name; config_name="$(echo -n "${config_params[config_param_index]}" | cut -d';' -f1 | xargs)"
        local setting_name; setting_name="$(echo -n "${config_params[config_param_index]}" | cut -d';' -f2 | xargs)"
        local setting_value; setting_value="$(grep -E "^[ \t]*${config_name}[ \t]*=[ \t]*.?" "$SETTINGS_FILE" | cut -d'=' -f2 | sed 's/^[ \t]*//;s/[ \t]*$//')"
        if [[ $? -ne 0 ]]; then
            Log "$0: No value for \"${config_name}\" using default."
            setting_value='default'
        fi
        echo "${BACKUP_PREFIX}-${setting_name}=${setting_value}" >>"${backup_file}"
        config_param_index=$((config_param_index + 1))
    done

    return $result
}

# Restore configuration parameters from backup file.
#
# input: backup file path
# output: returns config tool status, see /etc/config-tools/config_tool_defines.
#
function Restore
{
    local result=$SUCCESS;
    local backup_file="$1"

    config_param_index=0
    while [[ $config_param_index -lt ${#config_params[*]} ]]; do
        local config_name; config_name="$(echo -n "${config_params[config_param_index]}" | cut -d';' -f1 | xargs)"
        local setting_name; setting_name="$(echo -n "${config_params[config_param_index]}" | cut -d';' -f2 | xargs)"
        local setting_value; setting_value="$(grep -E "^[ \t]*${BACKUP_PREFIX}-${setting_name}[ \t]*=[ \t]*.?" "$backup_file" | tail -n1 | cut -d'=' -f2 | sed 's/^[ \t]*//;s/[ \t]*$//')"
        if [[ $? -ne 0 ]]; then
            # not set in backup file keeping currently set value
            Log "$0: Config \"${config_name}\" isn't included in backup file, skipping change."
        elif [[ "$setting_value" == "default" ]]; then
            # remove from config to use default
            sed -i -e "/^[ \t]*${config_name}[ \t]*=[ \t]*.*/d" "$SETTINGS_FILE"
            if [[ $? -ne 0 ]]; then
                Log "$0: Failed to write settings value for \"${config_name}\""
                result=$INTERNAL_ERROR
            fi
        else
            cat "$SETTINGS_FILE" | tr -d [[:blank:]] | /usr/bin/grep -q ^${config_name}=
            if [[ $? -ne 0 ]]; then
                echo "${config_name} = $setting_value" >> "$SETTINGS_FILE"
	            if [[ $? -ne 0 ]]; then
	                Log "$0: Failed to add settings value for \"${config_name}\""
	                result=$INTERNAL_ERROR
	            fi
            else
	            sed -i -e "s/^[ \t]*${config_name}[ \t]*=[ \t]*.*/${config_name} =${setting_value}/g" "$SETTINGS_FILE"
	            if [[ $? -ne 0 ]]; then
	                Log "$0: Failed to write settings value for \"${config_name}\""
	                result=$INTERNAL_ERROR
	            fi
          	fi
        fi
        config_param_index=$((config_param_index + 1))
    done
    return $result
}


#### MAIN ######################################################################

status=$SUCCESS

if [[ $# -ge 1 ]]; then
    operation="$1"

    if [[ $# -ge 2 ]]; then
        file="$2"
        if [[ "${operation}" == "--save" ]]; then
            Save "${file}"
            status=$?
        elif [[ "${operation}" == "--restore" ]]; then
            Restore "${file}"
            status=$?
        else
            # Unknown operation
            status=$INTERNAL_ERROR
            Log "$0: Unknown operation \"${operation}\""
        fi
    else
        if [[ "$operation" == "--param-count" ]]; then
            GetParameterCount
        elif [[ "$operation" == "-h" || "$operation" == "--help" ]]; then
            PrintUsage
        else
            # Unknown operation
            status=$INTERNAL_ERROR
            Log "$0: Unknown or incomplete operation \"$operation\""
        fi
    fi
fi

exit $status
