######################################################################
# Automatically generated by qmake (2.01a) Wed Apr 21 07:03:40 2010
######################################################################

TEMPLATE = app
TARGET = clear_screen
DEPENDPATH += .
INCLUDEPATH += .

QT += core gui widgets

# Input
SOURCES += clear_screen.cpp \
    tools.cpp

include(install.pri)

HEADERS += \
    clear_screen.h \
    tools.h \
    globals.h
