######################################################################
# Automatically generated by qmake (2.01a) Wed Apr 21 07:03:40 2010
######################################################################

TEMPLATE = app
TARGET = screensaverqt
DEPENDPATH += .
INCLUDEPATH += .

QT += core gui widgets x11extras
#LIBS += -lX11

# Input
SOURCES += screensaverqt.cpp \
    screensaver.cpp

include(install.pri)

HEADERS += \
    screensaver.h

