#!/bin/bash
#-----------------------------------------------------------------------------#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# This file is part of PTXdist package lighttpd.
#
# Copyright (c) 2025 WAGO GmbH & Co. KG
#-----------------------------------------------------------------------------#
#-----------------------------------------------------------------------------#
# Script:   /etc/config-tools/get_webserver_config
#
# Brief:    Tool to read webserver config (currently only certificate).
#
# Author:   PEn: WAGO GmbH & Co. KG
#-----------------------------------------------------------------------------#

# General definitions
readonly FAILEXIT=64
readonly SELF="$(/usr/bin/basename "$0")"
readonly WAGO_SYSTEM_MODULE="Webserver"
readonly WAGO_CT_TITLE="* Command line interface tool to read $WAGO_SYSTEM_MODULE config parameters *"
readonly CUSTOM_CERT="/etc/lighttpd/custom-cert.pem"

if [ ! -f "/etc/config-tools/config_tool_lib" ]; then
    echo "config_tool_lib missing"
    exit $FAILEXIT
fi
source "/etc/config-tools/config_tool_lib"


# Main tool/script function.
#
# Param 1..n: Script parameters
#
# Return: Exit code, 0 on success, unequal to 0 otherwise
#-----------------------------------------------------------------------------#
main()
{
    local result=0

    if [[ $# -lt 1 ]]; then
        print_info
        exit $FAILEXIT
    fi

    if [[ "$1" == "-h" || "$1" == "--help" ]]; then
        usage
        exit 0
    fi

    if [[ "$1" == certificate ]]; then
        read_certificate
        result=$?
    else
        result=$INVALID_PARAMETER
        SetLastError "Unable to find parameter \"$1\""
    fi

    return $result
}

# Function to print general tool/script information.
#
# Return: 0 on success, unequal to 0 otherwise
#-----------------------------------------------------------------------------#
print_info()
{
    echo "$WAGO_CT_TITLE"
    echo
    echo "For detailed usage information use:"
    echo "  $SELF --help"
    echo

    return 0
}

# Function to print usage to stdout.
#
# Return: 0 on success, unequal to 0 otherwise
#-----------------------------------------------------------------------------#
usage()
{
    echo "$WAGO_CT_TITLE"
    echo
    echo "Usage:"
    echo "  $SELF <config param name|-h|--help>"
    echo
    echo "Example:"
    echo "  $SELF certificate"
    echo "    Reads config value for \"certificate\""
    echo
}

# Function to read certificate.
#
# Return: 0 on success, unequal to 0 otherwise
#-----------------------------------------------------------------------------#
read_certificate()
{
    local result
    local value

    if [[ ! -e "$CUSTOM_CERT" ]]; then
        value=""
        result=$SUCCESS
    else
        value="$(base64 -w 100000 "$CUSTOM_CERT")"
        if [[ $? -ne 0 ]]; then
            result=$CONFIG_FILE_INCONSISTENT
            SetLastError "Failed to encode certificate file \"$CUSTOM_CERT\""
        else
            result=$SUCCESS
        fi
    fi
    if [[ result -eq $SUCCESS ]]; then
        printf "%s" "$value"
    fi

    return $result
}

# Start main function
main "$@"
exit $?
