#!/bin/bash
#-----------------------------------------------------------------------------#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# This file is part of project auth-service (PTXdist package wago-auth-service).
#
# Copyright (c) 2023 WAGO GmbH & Co. KG
#-----------------------------------------------------------------------------#
#-----------------------------------------------------------------------------#
# Script:   /etc/init.d/authd
#
# Brief:    System V init script for WAGO Auth Service.
#
# Author:   PEn: WAGO GmbH & Co. KG
#-----------------------------------------------------------------------------#

# General definitions
readonly FAILEXIT=1
readonly SELF="authd"
readonly WAGO_SYSTEM_MODULE="WAGO Auth Service"
readonly SERVICE_BIN="/usr/sbin/authd"
readonly WEB_API_BASE_PATH="/auth"
readonly WEB_API_SOCKET="/tmp/authserv.fcgi.socket"

# Check if online documentation is available
if [[ -f "/var/www/openapi/auth.openapi.html" ]]; then
    readonly DOCUMENTATION_BASE_URL="/openapi/auth.openapi.html"
else
    readonly DOCUMENTATION_BASE_URL=""
fi

# Function to print usage to stdout.
#
# Return: 0 on success, unequal to 0 otherwise
#-----------------------------------------------------------------------------#
usage()
{
    echo "$SELF usage: $0 <start|stop|restart|reload|status> [log-level for authd]"
}

# Function to start service functionality.
#
# Return: 0 on success, unequal to 0 otherwise
#-----------------------------------------------------------------------------#
auth_service_start()
{
    local result=0
    local log_option=""

    if [[ "$LOG_LEVEL" != "" ]]; then
        log_option="--log-level $LOG_LEVEL"
    fi

    # Start daemon process
    if ! /sbin/start-stop-daemon --start --background --quiet --oknodo --exec "${SERVICE_BIN}" -- \
            ${log_option} \
            --web-api-base "${WEB_API_BASE_PATH}" \
            --web-api-socket "${WEB_API_SOCKET}"; then
        result=$FAILEXIT
    # Check status of daemon: --background causes the start-stop-deamon not beeing able to detect any errors
    elif ! auth_service_status_check; then
        result=$FAILEXIT
    fi

    return $result
}

# Function to stop service functionality.
#
# Return: 0 on success, unequal to 0 otherwise
#-----------------------------------------------------------------------------#
auth_service_stop()
{
    local result=0

    # Stop daemon process
    if ! /sbin/start-stop-daemon --stop --quiet --oknodo --exec "$SERVICE_BIN"; then
        result=$FAILEXIT
    elif ! auth_service_status_check "stopped"; then
        result=$FAILEXIT
    fi

    return $result
}

# Function to reload the config.
#
# Return: 0 on success, unequal to 0 otherwise
#-----------------------------------------------------------------------------#
auth_service_reload()
{
    local result=0

    # Reload configuration files
    if ! /usr/bin/killall -SIGUSR1 "$SERVICE_BIN"; then
        result=$FAILEXIT
    fi

    return $result
}

# Function to check status of service functionality.
#
# Param 1: Optional parameter to check "started" or "stopped", default is check for "started"
#
# Return: 0 on success, unequal to 0 otherwise
#-----------------------------------------------------------------------------#
auth_service_status()
{
    local result=1
    local check="${1:-started}"
    local own_pid="$BASHPID"
    local pids
    pids="$(pidof "$(/usr/bin/basename "$SERVICE_BIN")")"
    for pid in $pids; do
        if [[ "$pid" != "$own_pid" ]]; then
            result=0
        fi
    done

    if [[ "$check" != "started" && $result -eq 0 ]]; then
        return 1
    elif [[ "$check" != "started" && $result -ne 0 ]]; then
        return 0
    fi

    return $result
}

# Function to check repeatedly status of service functionality.
#
# Param 1: Optional parameter to check "started" or "stopped", default is check for "started"
#
# Return: 0 on success, unequal to 0 otherwise
#-----------------------------------------------------------------------------#
auth_service_status_check()
{
    local result=0
    local check="${1:-started}"
    local check_count=3
    while ! auth_service_status "$check"
    do
        if [[ $check_count -gt 0 ]]; then
            /usr/bin/sleep 1
        else
            result=$FAILEXIT
            break
        fi
        check_count=$((check_count-1))
    done

    return $result
}

# Main switch
#-----------------------------------------------------------------------------#
LOG_LEVEL="${2:-}"
case $1 in
        start)
            echo "Starting ${WAGO_SYSTEM_MODULE}..."
            if ! auth_service_start; then
                echo "failed"
                exit $FAILEXIT
            else
                echo "done"
            fi
            ;;

        stop)
            echo "Stopping ${WAGO_SYSTEM_MODULE}..."
            if ! auth_service_stop; then
                echo "failed"
                exit $FAILEXIT
            else
                echo "done"
            fi
            ;;

        restart)
            echo "Restarting ${WAGO_SYSTEM_MODULE}..."
            if ! auth_service_stop; then
                echo "failed"
                exit $FAILEXIT
            else
                if ! auth_service_start; then
                    echo "failed"
                    exit $FAILEXIT
                else
                    echo "done"
                fi
            fi
            ;;

        reload)
            if ! auth_service_status; then
                echo "${WAGO_SYSTEM_MODULE} not running"
            else
                echo "Reloading ${WAGO_SYSTEM_MODULE}..."
                if ! auth_service_reload; then
                    echo "failed"
                    exit $FAILEXIT
                else
                    echo "done"
                fi
            fi
            ;;

        status)
            echo "Check status for ${WAGO_SYSTEM_MODULE}..."
            if ! auth_service_status; then
                echo "stopped"
            else
                echo "running"
            fi
            ;;

        *)
            usage
            exit $FAILEXIT
            ;;
esac
