#!/bin/bash

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2018-2022 WAGO GmbH & Co. KG

DIPSWITCHDIR=/dev/dip-switch

function log
{
    /usr/bin/logger -s -t networking "$@"
}

function has_marvell_switch
{
    if devlink dev info | grep -q '88E6321'; then
        return 0
    else
        return 1
    fi
}

function marvell_update_eeprom
{
   /sbin/pfcXXX_config_network_switch_eeprom.sh /sys/firmware/devicetree/base/ocp/interconnect@4a000000/segment@0/target-module@100000/switch@0/mdio@1000/switch@0/eeprom
   if [[ "$?" != "0" ]] ; then
        log "update switch eeprom failed"
   else
        log "update switch eeprom"
   fi
}

function networking_finish
{
    log "networking finish"

    [ -e  /etc/config-tools/config_switch ] && /etc/config-tools/config_switch --init

    if has_marvell_switch; then
        log "found marvell switch"
        marvell_update_eeprom
    fi
}

case "$1" in
start)
    networking_finish
    ;;
stop)
    ;;
reload)
    networking_finish
    ;;
restart|force-reload)
    networking_finish
    ;;
*)
    N=$BASH_COMMAND
    echo "usage: $N {start|restart|force-reload}" >&2
    exit 1
    ;;
esac

exit 0
