#
# Simple development makefile
#

#
# add more flags here,
# but don't remove the "+="
#
CFLAGS += -O2 -g -Wall -Wsign-compare -Wfloat-equal -Wformat-security -Werror
CPPFLAGS +=
LDFLAGS +=


all: si1142 si1142_client

clean:
	-rm -f si1142 si1142_client

install:


.PHONY: all install clean

# end of development makefile
