#!/bin/bash
#-----------------------------------------------------------------------------#
# Script-name: brightnesscontrol
#
# starting brightnesscontrol 
#
# Author: Wolfgang Rückl,  elrest GmbH
#-----------------------------------------------------------------------------#

# brightness_control (screensaverqt) needs a DISPLAY
. /etc/profile 2>&1 > /dev/null

PID=""
USESUDO=""

if [ $EUID != 0 ]; then
  USESUDO="sudo"
fi

function get_pid {
  PID=`pidof brightness_control`
}

function stop {
   get_pid
   if [ -z $PID ]; then
      echo "brightness_control is not running."
   else
      echo -n "stopping brightness_control .."
      $USESUDO killall -9 screensaverqt > /dev/null 2>&1
      $USESUDO killall -9 brightness_control > /dev/null 2>&1      
   fi
}


function start {
   get_pid
   if [ -z $PID ]; then
      echo  "starting brightness_control"
      $USESUDO /usr/bin/brightness_control &
      echo "done"
   else
      echo "brightness_control is already running, PID=$PID"
   fi
}

function restart {
   echo  "restarting brightness_control .."
   get_pid
   if [ -z $PID ]; then
      start
   else
      stop
      sleep 1
      start
   fi
}


function status {
   get_pid
   if [ -z $PID ]; then
      echo "brightness_control is not running."
   else
      echo "brightness_control is running, PID=$PID"
   fi
}

case "$1" in
   start)
      start
   ;;
   stop)
      stop
   ;;
   restart)
      restart
   ;;
   status)
      status
   ;;
   *)
      echo "usage: $0 {start|stop|restart|status}"
esac
