#!/bin/bash

file="/etc/pointercal"

myurldecode() { : "${*//+/ }"; echo -e "${_//%/\\x}"; }

# show help-text if requested
if [ $# -gt 0 ]; then
    if [ "$1" = "-h" -o "$1" = "--help" ]; then
        echo
        echo "* Restore touch-calibration file on resistive TP600 *"
        echo
        echo "Usage: config_pointercal -h | --help       	print this usage"
        echo "       config_pointercal <calibration_data>"
        exit 0
    else
        if [ -z "$1" ]; then
          #empty possible in captouch devices
          exit 0
        fi

        pcal=$(myurldecode "$1")
        
        #if [ -e "$file" ]; then
          echo "$pcal" > $file
        #fi
    fi
else
  exit 1
fi
