######################################################################
# Automatically generated by qmake (2.01a) Wed Apr 21 07:03:40 2010
######################################################################

TEMPLATE = app
TARGET = screen_care
DEPENDPATH += .
INCLUDEPATH += .

QT += core gui widgets

# Input
SOURCES += screen_care.cpp \
    screencare.cpp

include(install.pri)

HEADERS += \
    screencare.h

